#!/usr/bin/env bash
#Configuration of my server

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 100.25.164.167
    User ubuntu
